# Generated by Django 4.2.7 on 2025-12-04 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('categories', models.JSONField(default=list)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('service_radius', models.IntegerField(default=5)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'collectors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('estimated_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='collectors.collector')),
            ],
            options={
                'db_table': 'scrap_pickups',
                'ordering': ['-created_at'],
            },
        ),
    ]
